### ISSUE TITLE
can't execute seek due to a missing module

### ISSUE THREAD

**Issue by dlazarou** [cosmo-ethz/seek#12]
Can't execute SEEK command from notebook neither terminal, getting this:

```
Traceback (most recent call last):
  File "/Users/dimitrioslazarou/.local/bin/seek", line 11, in <module>
    load_entry_point('seek==0.1.0', 'console_scripts', 'seek')()
  File "/Users/dimitrioslazarou/anaconda3/envs/tf1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/dimitrioslazarou/anaconda3/envs/tf1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/dimitrioslazarou/anaconda3/envs/tf1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/dimitrioslazarou/anaconda3/envs/tf1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/dimitrioslazarou/anaconda3/envs/tf1/lib/python3.6/site-packages/ivy/__init__.py", line 7, in <module>
    import copy_reg
ModuleNotFoundError: No module named 'copy_reg'
```

I uninstalled and installed SEEK again from the repo, same issue

**Comment by dlazarou** [comment]
solved this by installing the correct ivy from the ETH repo:
https://github.com/cosmo-ethz/ivy/

Then I got 2 more error msgs that originate from the fact that ivy uses `UserDict` and `DictMixin` that are not supported in python 3.x.
Workaround was to use the `collection` class and add into `struct.py` in `ivy/utils` folder the following:
```
#fixed by using:
from collections import UserDict
#fixed also by using:
from collections import MutableMapping as DictMixin
```

After this fix I started getting other errors as the code progresses:
```
File "/Users/dimitrioslazarou/anaconda3/envs/tf1/lib/python3.6/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, MutableMapping
``` ,
that seem more fundamental :)

Maybe i need to set the correct environment but i don't know the exact versions of packages that
 this notebook uses: https://github.com/jakeret/tf_unet/blob/master/demo/demo_radio_data.ipynb
I just want to reproduce it ^.

**Comment by uweschmitt** [comment]
We renamed "our" `ivy` to `ivy-wfengine` a while ago in order to avoid this confusion. Regrettably some `setup.py` files are not adapted to this.
