### ISSUE TITLE
Anyone who has installed seek recently?

### ISSUE THREAD

**Issue by dlazarou** [cosmo-ethz/seek#13]
Hi community!

Anyone who has installed seek recently? Can you specify the environment, packages version etc?

And which guide you followed?

Thanks!

**Comment by dlazarou** [comment]
@uweschmitt

**Comment by uweschmitt** [comment]
Better ask @jakeret, the original author.

**Comment by dlazarou** [comment]
@jakeret

**Comment by uweschmitt** [comment]
@dlazarou I created a fork with needed fixes which is available at  https://cosmo-gitlab.phys.ethz.ch/cosmo_public/seek

It works with `Python 2.7` and recente `numpy`.

**Comment by dlazarou** [comment]
Thanks a lot! SEEK was installed sucessfully in a venv with Python 2.7, however i am getting the error:

`/seek/plugins/find_nested_files.py", line 144, in __call__
assert len(data_file_paths)!=0 or len(calibrations_paths)!=0, "No files match requirements"`

when i try to run seek by using:

`seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft`
from command line.

Files are coming from here:
https://people.phys.ethz.ch/~ipa/cosmo/bgs_example_data/2016/03/21/
Do they have the correct format?

**Comment by uweschmitt** [comment]
`seek` also expects  subfolders `bgs_example_data/2015/...` which do not exist at `https://people.phys.ethz.ch/~ipa/cosmo/bgs_example_data/`.

`2015` is hard coded in `seek` at https://cosmo-gitlab.phys.ethz.ch/cosmo_public/seek/blob/master/seek/config/process_survey.py#L66

**Comment by dlazarou** [comment]
Oh i see, that was really helpful sir. I see that the file suffix is also different.

1. To your knowledge, is there a web address where i can use `wget` and get files?
2. Are the files in the link above suitable for `seek` if i change something in the hard-coded part?

What i try to do is reproduce the jupyter notebook:
https://github.com/jakeret/tf_unet/blob/master/demo/demo_radio_data.ipynb
but any data in which i can use `seek` would be suitable.

PS: I still use `seek` from the original repo, not yours. Should i clone yours instead?

**Comment by uweschmitt** [comment]
1. No, don't know.
2. Also don't know. But will ask around

I suggest to ask @jakeret as he wrote the notebook.

Please use the clone, we plan to remove duplicated code and the github version is the current candidate to be shut down.

**Comment by dlazarou** [comment]
So maybe a solution is to create data through HIDE.

Installing HIDE, got the same error in both MacOS and Ubuntu (utf encoding! ). Don't know if someone monitors this repo hence I post it here.

https://github.com/cosmo-ethz/hide/issues/5

**Comment by carlosotobone** [comment]
@dlazarou 

Hello, my collaborator and I have been getting the same error: 

`File "/usr/local/lib/python2.7/dist-packages/seek-0.1.0-py2.7.egg/seek/plugins/find_nested_files.py", line 144, in __call__
    assert len(data_file_paths)!=0 or len(calibrations_paths)!=0, "No files match requirements"`

**Have you found any solutions?**

We are using the data produced by HIDE.

**Comment by mesarcik** [comment]
I have managed to install seek in 2021 using python2.7.  I needed to do the following things to get it to work:

1. Download the data from the Bleien telescope using
 `wget -q -r -nH -np --cut-dirs=2 https://people.phys.ethz.ch/~ipa/cosmo/bgs_example_data/ `
2. Make the cache directory 
    `mkdir -p bgs_example_data/seek_cache ` 
3. Follow the[ installation guide of seek](https://seek.readthedocs.io/en/latest/installation.html), except ensure you install the following package versions:
    ```
            numpy==1.16.0
            healpy==1.10.2
            astropy==1.2.1     
    ```
4. It seems that the installation does not copy the `data` directory into the correct location. So you will need to copy the data directory from the cloned repository to the installed location of the desired python environment. 

5. This should allow you to run
````
seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft
````

I hope this helps someone :)

**Comment by itachi-gf** [comment]
> I have managed to install seek in 2021 using python2.7. I needed to do the following things to get it to work:
> 
> 1. Download the data from the Bleien telescope using
>    `wget -q -r -nH -np --cut-dirs=2 https://people.phys.ethz.ch/~ipa/cosmo/bgs_example_data/ `
> 2. Make the cache directory
>    `mkdir -p bgs_example_data/seek_cache `
> 3. Follow the[ installation guide of seek](https://seek.readthedocs.io/en/latest/installation.html), except ensure you install the following package versions:
>    ```
>            numpy==1.16.0
>            healpy==1.10.2
>            astropy==1.2.1     
>    ```
> 4. It seems that the installation does not copy the `data` directory into the correct location. So you will need to copy the data directory from the cloned repository to the installed location of the desired python environment.
> 5. This should allow you to run
> 
> ```
> seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft
> ```
> 
> I hope this helps someone :)

After following the steps you provided, I encountered the following error:
Total number of days found:  1
Total number of calibration days found:  0
Traceback (most recent call last):
  File "/home/gufei/.local/bin/seek", line 11, in <module>
    load_entry_point('seek==0.1.0', 'console_scripts', 'seek')()
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run
    _main(*sys.argv[1:])
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main
    mgr.launch()
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch
    executor.run(ctx().params.plugins)
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
    return map(LoopWrapper(loop), mapPlugin.getWorkload())
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 129, in __call__
    plugin()
  File "/home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/plugins/calibration.py", line 34, in __call__
    self.ctx.gain_file = load_file(self.ctx.params.gain_file_default)
  File "/home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/utils/__init__.py", line 44, in load_file
    return np.genfromtxt(path, **kwargs)
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1737, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
IOError: /home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/data/gain_template_7m_FFT_phase_switch_ADU_K.dat not found.

Did you mean to copy the data directory to the site-packages in my Python environment?

Thank you very much for your help.

**Comment by mesarcik** [comment]
> > I have managed to install seek in 2021 using python2.7. I needed to do the following things to get it to work:
> > 
> > 1. Download the data from the Bleien telescope using
> >    `wget -q -r -nH -np --cut-dirs=2 https://people.phys.ethz.ch/~ipa/cosmo/bgs_example_data/ `
> > 2. Make the cache directory
> >    `mkdir -p bgs_example_data/seek_cache `
> > 3. Follow the[ installation guide of seek](https://seek.readthedocs.io/en/latest/installation.html), except ensure you install the following package versions:
> >    ```
> >            numpy==1.16.0
> >            healpy==1.10.2
> >            astropy==1.2.1     
> >    ```
> > 4. It seems that the installation does not copy the `data` directory into the correct location. So you will need to copy the data directory from the cloned repository to the installed location of the desired python environment.
> > 5. This should allow you to run
> > 
> > ```
> > seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this helps someone :)
> 
> After following the steps you provided, I encountered the following error: Total number of days found: 1 Total number of calibration days found: 0 Traceback (most recent call last): File "/home/gufei/.local/bin/seek", line 11, in load_entry_point('seek==0.1.0', 'console_scripts', 'seek')() File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run _main(*sys.argv[1:]) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main mgr.launch() File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch executor.run(ctx().params.plugins) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 48, in run return map(LoopWrapper(loop), mapPlugin.getWorkload()) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 129, in **call** plugin() File "/home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/plugins/calibration.py", line 34, in **call** self.ctx.gain_file = load_file(self.ctx.params.gain_file_default) File "/home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/utils/**init**.py", line 44, in load_file return np.genfromtxt(path, **kwargs) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1737, in genfromtxt fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding)) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 266, in open return ds.open(path, mode, encoding=encoding, newline=newline) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 623, in open raise IOError("%s not found." % path) IOError: /home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/data/gain_template_7m_FFT_phase_switch_ADU_K.dat not found.
> 
> Did you mean to copy the data directory to the site-packages in my Python environment?
> 
> Thank you very much for your help.

Yes, I meant copying the data from https://github.com/cosmo-ethz/seek/tree/master/seek/data to the appropriate location in the local installation, in your case to`/home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/data`

**Comment by itachi-gf** [comment]
> seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft
I have copied the data into my Python environment as you suggested.I've resolved the error.However, I've encountered another error：
(seek2_7) gufei@AB24:~/rfi_code/final_hide_seek/seek/data$ seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft
Traceback (most recent call last):
  File "/home/gufei/.local/bin/seek", line 11, in <module>
    load_entry_point('seek==0.1.0', 'console_scripts', 'seek')()
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run
    _main(*sys.argv[1:])
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main
    mgr.launch()
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch
    executor.run(ctx().params.plugins)
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
    return map(LoopWrapper(loop), mapPlugin.getWorkload())
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 126, in __call__
    for plugin in self.loop:
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/loop.py", line 95, in next
    return self._instantiate(plugin)
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/loop.py", line 136, in _instantiate
    return PluginFactory.createInstance(pluginName, self.ctx)
  File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/plugin/plugin_factory.py", line 59, in createInstance
    raise UnsupportedPluginTypeException("Module '%s' could not be instantiated'" % pluginName, ex)
ivy.exceptions.exceptions.UnsupportedPluginTypeException: (u"Module 'seek.plugins.initialize' could not be instantiated'", ValueError(u"Coordinate frame barycentricmeanecliptic not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'precessedgeocentric', 'supergalactic']",))

What should I do next?

**Comment by itachi-gf** [comment]
> > > I have managed to install seek in 2021 using python2.7. I needed to do the following things to get it to work:
> > > 
> > > 1. Download the data from the Bleien telescope using
> > >    `wget -q -r -nH -np --cut-dirs=2 https://people.phys.ethz.ch/~ipa/cosmo/bgs_example_data/ `
> > > 2. Make the cache directory
> > >    `mkdir -p bgs_example_data/seek_cache `
> > > 3. Follow the[ installation guide of seek](https://seek.readthedocs.io/en/latest/installation.html), except ensure you install the following package versions:
> > >    ```
> > >            numpy==1.16.0
> > >            healpy==1.10.2
> > >            astropy==1.2.1     
> > >    ```
> > > 4. It seems that the installation does not copy the `data` directory into the correct location. So you will need to copy the data directory from the cloned repository to the installed location of the desired python environment.
> > > 5. This should allow you to run
> > > 
> > > ```
> > > seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I hope this helps someone :)
> > 
> > 
> > After following the steps you provided, I encountered the following error: Total number of days found: 1 Total number of calibration days found: 0 Traceback (most recent call last): File "/home/gufei/.local/bin/seek", line 11, in load_entry_point('seek==0.1.0', 'console_scripts', 'seek')() File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run _main(*sys.argv[1:]) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main mgr.launch() File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch executor.run(ctx().params.plugins) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 48, in run return map(LoopWrapper(loop), mapPlugin.getWorkload()) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 129, in **call** plugin() File "/home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/plugins/calibration.py", line 34, in **call** self.ctx.gain_file = load_file(self.ctx.params.gain_file_default) File "/home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/utils/**init**.py", line 44, in load_file return np.genfromtxt(path, **kwargs) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1737, in genfromtxt fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding)) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 266, in open return ds.open(path, mode, encoding=encoding, newline=newline) File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 623, in open raise IOError("%s not found." % path) IOError: /home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/data/gain_template_7m_FFT_phase_switch_ADU_K.dat not found.
> > Did you mean to copy the data directory to the site-packages in my Python environment?
> > Thank you very much for your help.
> 
> Yes, I meant copying the data from https://github.com/cosmo-ethz/seek/tree/master/seek/data to the appropriate location in the local installation, in your case to`/home/gufei/.local/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/data`

I have copied the data into my Python environment as you suggested.I've resolved the error.However, I've encountered another error：
(seek2_7) gufei@AB24:~/rfi_code/final_hide_seek/seek/data$ seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft
Traceback (most recent call last):
File "/home/gufei/.local/bin/seek", line 11, in
load_entry_point('seek==0.1.0', 'console_scripts', 'seek')()
File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 28, in run
_main(*sys.argv[1:])
File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/cli/main.py", line 37, in _main
mgr.launch()
File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/workflow_manager.py", line 107, in launch
executor.run(ctx().params.plugins)
File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 48, in run
return map(LoopWrapper(loop), mapPlugin.getWorkload())
File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/backend.py", line 126, in call
for plugin in self.loop:
File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/loop.py", line 95, in next
return self._instantiate(plugin)
File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/loop.py", line 136, in _instantiate
return PluginFactory.createInstance(pluginName, self.ctx)
File "/home/gufei/mambaforge/envs/seek2_7/lib/python2.7/site-packages/ivy/plugin/plugin_factory.py", line 59, in createInstance
raise UnsupportedPluginTypeException("Module '%s' could not be instantiated'" % pluginName, ex)
ivy.exceptions.exceptions.UnsupportedPluginTypeException: (u"Module 'seek.plugins.initialize' could not be instantiated'", ValueError(u"Coordinate frame barycentricmeanecliptic not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'precessedgeocentric', 'supergalactic']",))

What should I do next?
