### ISSUE TITLE
Using SEEK for calibrating HIDE data

### ISSUE THREAD

**Issue by etienne-v** [cosmo-ethz/seek#9]
After using the example given in the HIDE documentation to generate data along with RFI, I want to calibrate the data using SEEK.  If the command for producing the data with HIDE is:
$ hide --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m

... is it as simple as replacing 'hide' with 'seek' to do the calibration?  As in:
$ seek --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m

**Comment by jakeret** [comment]
Phew a lot of time has passed since..
As you can see in the [documentation](http://seek.readthedocs.io/en/latest/usage.html) the command is quite similar:
```
$ seek --file-prefix=./hide_data --map-name=maps.hdf --verbose=True seek.config.process_survey_fft
```

**Comment by etienne-v** [comment]
Thanks @jakeret 
I did look at the documentation but weren't able to successfully run seek calibration on the data produced by the HIDE example.  
With the .h5 data files located in a ./hide_data folder, with filenames "TEST_MP_PXX_20160321_******.h5", using the command from the documentation:

$ seek --file-prefix=./hide_data --data-file-prefix="TEST_MP_PXX_" --map_name-maps.hdf --verbose=True seek.config.process_survey_fft

... produces a "No files match requirements" error.  Including the --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 flags to this gives a "Local variable 'ctx' referenced before assignment" error.  Are there config files for both HIDE and SEEK that work out of the box and can serve as an example?

**Comment by jakeret** [comment]
Could you provide the entire error message? If I remember correctly this is just a minor thing to fix.

Unfortunately, there are no more examples available. The package is no longer being developed any further

**Comment by etienne-v** [comment]
What I do is the following:

Use the example from HIDE to produce the data files:
`$ hide --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m
`
I move the `2016/` folder into a different folder named `hide_data`, and run the following command with seek:
`$ seek --file-prefix=./hide_data --data-file-prefix="TEST_MP_PXX_" --map-name=maps.hdf --verbose=True seek.config.process_survey_fft`

This gives the following output and error message:

> Total number of days found:  0
> Total number of calibration days found:  1
> Traceback (most recent call last):
>   File "/opt/conda/bin/seek", line 11, in <module>
>     load_entry_point('seek==0.1.0', 'console_scripts', 'seek')()
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/cli/main.py", line 28, in run
>     _main(*sys.argv[1:])
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/cli/main.py", line 37, in _main
>     mgr.launch()
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/workflow_manager.py", line 107, in launch
>     executor.run(ctx().params.plugins)
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/backend.py", line 48, in run
>     return map(LoopWrapper(loop), mapPlugin.getWorkload())
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/backend.py", line 129, in __call__
>     plugin()
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/plugin/parallel_plugin_collection.py", line 88, in __call__
>     reducePlugin.reduce(ctxList)
>   File "/opt/conda/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/plugins/reduce_map_indicies.py", line 39, in reduce
>     self.ctx.frequencies = ctx.frequencies
> UnboundLocalError: local variable 'ctx' referenced before assignment
> 

Any help will be much appreciated... thanks!

**Comment by jakeret** [comment]
Have you tried to generate more data? Looks like you have one day of calibration data and 0 days with actual data collection.
Seems like that this case is not properly handled

**Comment by etienne-v** [comment]
Thanks... I didn't realize that.

I generated a month's worth of data now (5 calibration days & 26 data collection days).  Here's what I did:
`$ hide --strategy-start=2016-03-01-00:00:00 --strategy-end=2016-04-01-00:00:00 --verbose=True hide.config.bleien7m`

And then used seek as usual:
`seek --file-prefix=./hide_data --data-file-prefix="TEST_MP_PXX_" --map-name=maps.hdf --verbose=True seek.config.process_survey_fft`

which produced:

>Total number of days found:  26
> Total number of calibration days found:  5
> Current files: ./hide_data/2016/03/02/TEST_MP_PXX_20160302_000000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_001500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_003000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_004500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_010000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_011500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_013000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_014500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_020000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_021500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_023000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_024500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_030000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_031500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_033000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_034500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_040000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_041500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_043000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_044500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_050000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_051500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_053000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_054500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_060000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_061500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_063000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_064500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_070000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_071500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_073000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_074500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_080000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_081500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_083000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_084500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_090000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_091500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_093000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_094500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_100000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_101500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_103000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_104500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_110000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_111500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_113000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_114500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_120000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_121500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_123000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_124500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_130000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_131500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_133000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_134500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_140000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_141500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_143000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_144500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_150000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_151500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_153000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_154500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_160000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_161500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_163000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_164500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_170000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_171500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_173000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_174500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_180000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_181500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_183000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_184500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_190000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_191500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_193000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_194500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_200000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_201500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_203000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_204500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_210000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_211500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_213000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_214500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_220000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_221500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_223000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_224500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_230000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_231500.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_233000.h5
> ./hide_data/2016/03/02/TEST_MP_PXX_20160302_234500.h5
> Traceback (most recent call last):
>   File "/opt/conda/bin/seek", line 11, in <module>
>     load_entry_point('seek==0.1.0', 'console_scripts', 'seek')()
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/cli/main.py", line 28, in run
>     _main(*sys.argv[1:])
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/cli/main.py", line 37, in _main
>     mgr.launch()
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/workflow_manager.py", line 107, in launch
>     executor.run(ctx().params.plugins)
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/backend.py", line 48, in run
>     return map(LoopWrapper(loop), mapPlugin.getWorkload())
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/backend.py", line 129, in __call__
>     plugin()
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/plugin/parallel_plugin_collection.py", line 81, in __call__
>     ctxList = backendImpl.run(self.pluginList, mapPlugin)
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/backend.py", line 48, in run
>     return map(LoopWrapper(loop), mapPlugin.getWorkload())
>   File "/opt/conda/lib/python2.7/site-packages/ivy-0.1.0-py2.7.egg/ivy/backend.py", line 129, in __call__
>     plugin()
>   File "/opt/conda/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/plugins/post_process_tod.py", line 42, in __call__
>     with h5py.File(filepath, "w") as fp:
>   File "/opt/conda/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
>     fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
>   File "/opt/conda/lib/python2.7/site-packages/h5py/_hl/files.py", line 107, in make_fid
>     fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 98, in h5py.h5f.create
> IOError: Unable to create file (Unable to open file: name = '.cache/test_mp_pxx_20160302_000000.h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)


So seems like a little progress... any ideas on the above error?  Seems like it's looking for the files in .cache/.

**Comment by jakeret** [comment]
Yeah looks better now. Have you tried to create that folder prior to the run?

**Comment by etienne-v** [comment]
Thanks @jakeret ... that worked.  One last question (hopefully) - is it possible to have HIDE generate different kinds of signals and RFI patterns... maybe a time-varying signal or so.  Anything that I can change so that both the signal and RFI looks different or changes with time?
Thanks!

**Comment by jakeret** [comment]
sorry for the very late reply.
The signal is comes from GSM and varies over time based on your scanning strategy. The [RFI model ](https://github.com/cosmo-ethz/hide/blob/master/hide/plugins/add_rfi.py)is relatively simple but already has a time variation (e.g. less rfi during the night)

**Comment by etienne-v** [comment]
Got it... thanks @jakeret.  So that wasn't the last question...
I managed to produce a couple of datasets with HIDE using different parameters and applied seek to uncalibrated HIDE outputs.  However, the calibrated .h5 outputs from seek don't contain the "RFI" group as the uncalibrated ones do.  If I run
`$ h5dump --header TEST_MP_PXX_20170104_003000.h5`
on one of the HIDE outputs, I can see the "RFI" group which contains the RFI information:
> HDF5 "TEST_MP_PXX_20170104_003000.h5" {
> GROUP "/" {
>    DATASET "FREQUENCY" {
>       DATATYPE  H5T_IEEE_F64LE
>       DATASPACE  SIMPLE { ( 276 ) / ( 276 ) }
>    }
>    GROUP "P" {
>       DATASET "Phase0" {
>          DATATYPE  H5T_IEEE_F64LE
>          DATASPACE  SIMPLE { ( 276, 150 ) / ( 276, 150 ) }
>       }
>       DATASET "Phase1" {
>          DATATYPE  H5T_IEEE_F64LE
>          DATASPACE  SIMPLE { ( 276, 150 ) / ( 276, 150 ) }
>       }
>    }
>    GROUP "RFI" {
>       DATASET "Phase0" {
>          DATATYPE  H5T_IEEE_F64LE
>          DATASPACE  SIMPLE { ( 276, 150 ) / ( 276, 150 ) }
>       }
>       DATASET "Phase1" {
>          DATATYPE  H5T_IEEE_F64LE
>          DATASPACE  SIMPLE { ( 276, 150 ) / ( 276, 150 ) }
>       }
>    }
>    DATASET "TIME" {
>       DATATYPE  H5T_STD_I64LE
>       DATASPACE  SIMPLE { ( 150 ) / ( 150 ) }
>    }
> }
> }

...whereas running
`h5dump --header TEST_MP_PXX_20170104_000000.h5 `
on one of the SEEK output files gives:

> HDF5 "TEST_MP_PXX_20170104_000000.h5" {
> GROUP "/" {
>    DATASET "data" {
>       DATATYPE  H5T_IEEE_F64LE
>       DATASPACE  SIMPLE { ( 13, 14400 ) / ( 13, 14400 ) }
>    }
>    DATASET "dec" {
>       DATATYPE  H5T_IEEE_F64LE
>       DATASPACE  SIMPLE { ( 14400 ) / ( 14400 ) }
>    }
>    DATASET "frequencies" {
>       DATATYPE  H5T_IEEE_F64LE
>       DATASPACE  SIMPLE { ( 13 ) / ( 13 ) }
>    }
>    DATASET "mask" {
>       DATATYPE  H5T_ENUM {
>          H5T_STD_I8LE;
>          "FALSE"            0;
>          "TRUE"             1;
>       }
>       DATASPACE  SIMPLE { ( 13, 14400 ) / ( 13, 14400 ) }
>    }
>    DATASET "ra" {
>       DATATYPE  H5T_IEEE_F64LE
>       DATASPACE  SIMPLE { ( 14400 ) / ( 14400 ) }
>    }
>    DATASET "ref_channel" {
>       DATATYPE  H5T_IEEE_F64LE
>       DATASPACE  SIMPLE { ( 14400 ) / ( 14400 ) }
>    }
>    DATASET "time" {
>       DATATYPE  H5T_IEEE_F64LE
>       DATASPACE  SIMPLE { ( 14400 ) / ( 14400 ) }
>    }
> }
> }

Is there a flag that I should pass in order to keep the (calibrated) RFI information in the final outputs?

**Comment by jakeret** [comment]
The RFI actually doesn't get calibrated. SEEK applies a RFI mitigation algorithm in order to mask the inference.

**Comment by etienne-v** [comment]
Thanks @jakeret 

I've been trying to get hold of you via the email in your paper titled "Radio frequency interference mitigation using deep convolutional neural networks" without success... I'm interested in using the actual Bleien telescope observations (as given in Figure 2 of your paper) in combination with the HIDE&SEEK simulations.  Let me know if you can help me with this and if you have a preferred method of contact.  Thanks!

**Comment by jakeret** [comment]
sorry for not responding. I left academia a while ago and my old email is no longer active. I maintain the `tf_unet` package in my spare time but otherwise I have little contact with my former institute. Maybe you can get some help from @uweschmitt

**Comment by etienne-v** [comment]
@jakeret One last question with regard to HIDE & SEEK - am I correct if I say that HIDE only produces magnitude spectra and that phase information is not available?
